name: care
description: "CARES (Comprehensive Auto Repair & Emergency Services)"
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.5.2
  fluttertoast: ^8.2.12
  open_file: ^3.5.10
  package_info_plus: ^8.3.0
  permission_handler: ^11.4.0
  path_provider: ^2.1.5
  wakelock_plus: ^1.3.2
  unique_identifier: ^0.4.0
  google_sign_in: ^6.1.5
  flutter_secure_storage: ^9.2.4
  uuid: ^4.5.1
  image_picker: ^1.1.2
  connectivity_plus: ^6.1.4
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  flutter_polyline_points: ^3.0.1
  location: ^8.0.1
  intl: ^0.20.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.jpg"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Lato-Black
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
    - family: Lato-Italic
      fonts:
        - asset: assets/fonts/Lato-Italic.ttf
          weight: 600

